spring.shardingsphere.datasource.config.driver-class-name=org.postgresql.Driver
spring.shardingsphere.datasource.config.url=jdbc:postgresql://127.0.0.1:5432/config
spring.shardingsphere.datasource.config.password=123456
spring.shardingsphere.datasource.config.type=com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.config.username=postgres


spring.shardingsphere.datasource.ds0.driver-class-name=org.postgresql.Driver
spring.shardingsphere.datasource.ds0.url=jdbc:postgresql://127.0.0.1:5432/test1
spring.shardingsphere.datasource.ds0.password=123456
spring.shardingsphere.datasource.ds0.type=com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.ds0.username=postgres

spring.shardingsphere.datasource.ds1.driver-class-name=org.postgresql.Driver
spring.shardingsphere.datasource.ds1.url=jdbc:postgresql://127.0.0.1:5432/test2
spring.shardingsphere.datasource.ds1.password=123456
spring.shardingsphere.datasource.ds1.type=com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.ds1.username=postgres

spring.shardingsphere.datasource.names=ds0,ds1,config



spring.shardingsphere.sharding.tables.client_config.actual-data-nodes=config.client_config
spring.shardingsphere.sharding.tables.t_order.actual-data-nodes=ds${0..1}.t_order
#
spring.shardingsphere.sharding.tables.t_order.database-strategy.hint.algorithm-class-name=com.example.shardingspherebase.algorithm.HintShardingKeyAlgorithm

spring.shardingsphere.sharding.default-database-strategy.hint.algorithm-class-name=com.example.shardingspherebase.algorithm.HintShardingKeyAlgorithm

spring.shardingsphere.props.sql.show=true
mybatis.mapper-locations=classpath:mapper/*.xml